Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/02/2024
Var
// Seção de Declarações das variáveis 

   x : inteiro
   y : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


   x <- 5
   y <- 2 * x
   escreval(x)
   escreval(y)

Fimalgoritmo