Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/02/2024
Var
// Seção de Declarações das variáveis 
   b1, b2, h, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   b1 <- 6.0
   b2 <- 8.0
   h <- 5.0
   
   area <- (b1+b2)/2.0 * h
   
   escreval(area)

Fimalgoritmo