Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/02/2024
Var
// Seção de Declarações das variáveis 

   a: real
   b: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   a <- 5.3
   b <- Int(a)
   escreval(b)

Fimalgoritmo