Algoritmo "nao_e"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Dr. Nelio Alves
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2024
Var
   // Seção de Declarações das variáveis
   x : inteiro

Inicio
   // Seção de Comand os, procedimento, funções, operadores, etc...
   x <- 5
   nao ((x=10)e(x<=20))
Fimalgoritmo