Algoritmo "soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2024
Var
// Seção de Declarações das variáveis 
x, y : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digiite o valor de x: ")
leia(x)
escreva("Digite o valor de y: ")
leia(y)
escreva("Soma = ", x+y)
Fimalgoritmo