Algoritmo "teste_saida"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/02/2024
Var

   a: inteiro
   b: real
   c: caractere
   d: logico

Inicio


      a <- 32
      b <- 2.34565
      c <- "Bom dia!"
      d <- verdadeiro

      escreval(a)
      escreval(b:10:2)
      escreval(c)
      escreval(d)

Fimalgoritmo